version: '3'

services:
  convert:
    build:
      context: .
      dockerfile: docker/convert/Dockerfile
    image: moorelab/kragen-convert:${TAG}
    volumes:
      - "./:/usr/src/app"
    working_dir: /usr/src/app
    entrypoint: ["python", "src/kragen.py"]
    command: test.csv