version: '3'

services:
  kragen:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        docker_files: 'docker'
    image: moorelab/kragen:${TAG}
    volumes:
      - "./:/usr/src/app"
    working_dir: /usr/src/app
    entrypoint: ["python", "src/kragen.py"]
    env_file:
      - .env
      - config/kragen.env
    depends_on:
      - weaviate
    # command: test.csv

  weaviate:
    extends:
      file: docker-compose-weaviate.yml
      service: weaviate