services:
  kragen:
    extends:
      file: docker-compose-kragen.yml
      service: kragen
    depends_on:
      - weaviate
    networks:
      - kragen-net

  weaviate:
    extends:
      file: docker-compose-weaviate.yml
      service: weaviate
    networks:
      - kragen-net

  execgpt:
    extends:
      file: docker-compose-flask.yml
      service: execgpt
    depends_on:
      - weaviate
    networks:
      - kragen-net

  gui:
    extends:
      file: docker-compose-gui.yml
      service: gui
    depends_on:
      - execgpt
    networks:
      - kragen-net

networks:
  kragen-net:
    driver: bridge
