services:
  execgpt:
    build:
      context: ./KRAGEN_Dashboard/Backend
      dockerfile: Dockerfile
    # image: moorelab/${IMAGE_NAME}:${TAG}
    image: kragen-server:${TAG}
    container_name: kragen-server
    ports:
      - 5050:5050
    # entrypoint: ["python", "src/kragen.py"]
    env_file:
      - .env
      - config/kragen.env
