version: '3'

services:
  convert:
    build:
      context: .
      dockerfile: docker/convert/Dockerfile
    image: moorelab/krag-convert:${TAG}
    volumes:
      - "./:/data"
    working_dir: /data
